"""increase_description_length_to_500

Revision ID: 175c9fc3a15e
Revises: a2c3adeaeb3a
Create Date: 2025-06-27 20:37:40.061827+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175c9fc3a15e'
down_revision: Union[str, None] = 'a2c3adeaeb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('uq_collection_album', 'collection_album', ['collection_id', 'album_id'])
    op.alter_column('places', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'description',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    #op.drop_constraint('uq_collection_album', 'collection_album', type_='unique')
    # ### end Alembic commands ###
