"""initial clean DB for VinylKeeper

Revision ID: 420295606859
Revises: 0001_create_all_enums
Create Date: 2025-06-15 06:49:48.481127+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420295606859'
down_revision: Union[str, None] = '0001_create_all_enums'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Enum('ADMIN', 'USER', 'MODERATOR',
                              name='roleenum', create_type=False), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password', sa.String(
                        length=1024), nullable=False),
                    sa.Column('is_accepted_terms',
                              sa.Boolean(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('last_login', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('registered_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('timezone', sa.String(length=100),
                              server_default='Europe/Paris', nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('user_uuid', sa.UUID(), nullable=False),
                    sa.Column('number_of_connections',
                              sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_uuid')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'),
                    'users', ['username'], unique=True)
    op.create_table('albums',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('external_album_id', sa.String(
                        length=255), nullable=False, comment='External Album ID as string'),
                    sa.Column('source', sa.Enum('DEEZER', 'SPOTIFY', 'MUSICBRAINZ', 'DISCOGS', 'LAST_FM', name='externalsourceenum',
                                                create_type=False), server_default='DISCOGS', nullable=False, comment='Source of the external album ID'),
                    sa.Column('title', sa.String(length=512), nullable=True,
                              comment='Cached title of the album'),
                    sa.Column('image_url', sa.String(length=1024), nullable=True,
                              comment='Cached cover image URL for the album'),
                    sa.Column('owner_id', sa.Integer(), nullable=False,
                              comment='ID of the user who owns this album'),
                    sa.Column('state_record', sa.Enum('MINT', 'NEAR_MINT', 'VERY_GOOD', 'GOOD', 'FAIR', 'POOR',
                                                      name='stateenum', create_type=False), nullable=True, comment='Physical state of the vinyl record'),
                    sa.Column('state_cover', sa.Enum('MINT', 'NEAR_MINT', 'VERY_GOOD', 'GOOD', 'FAIR', 'POOR',
                                                     name='stateenum', create_type=False), nullable=True, comment='Physical state of the album cover'),
                    sa.Column('mood', sa.Enum('HAPPY', 'SAD', 'EXCITED', 'CALM', 'ANGRY', 'RELAXED', 'ENERGETIC',
                                              'MELANCHOLIC', name='moodenum', create_type=False), nullable=True, comment='Mood associated with this album'),
                    sa.Column('acquisition_date', sa.DateTime(), nullable=True,
                              comment='Date when the album was acquired'),
                    sa.Column('purchase_price', sa.Integer(), nullable=True,
                              comment='Price paid for the album in cents'),
                    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text(
                        'now()'), nullable=False, comment='When the album was first registered'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(
                        'now()'), nullable=False, comment='When the album was last updated'),
                    sa.ForeignKeyConstraint(
                        ['owner_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('external_album_id', 'source',
                                        name='uq_external_album_id_source')
                    )
    op.create_index(op.f('ix_albums_external_album_id'),
                    'albums', ['external_album_id'], unique=True)
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    op.create_index(op.f('ix_albums_owner_id'),
                    'albums', ['owner_id'], unique=False)
    op.create_table('artists',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('discogs_artist_id', sa.String(
                        length=255), nullable=False, comment='Discogs Artist ID as string'),
                    sa.Column('owner_id', sa.Integer(), nullable=False,
                              comment='ID of the user who owns this artist entry'),
                    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text(
                        'now()'), nullable=False, comment='When the artist was first registered'),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(
                        'now()'), nullable=False, comment='When the artist was last updated'),
                    sa.ForeignKeyConstraint(
                        ['owner_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_artists_discogs_artist_id'),
                    'artists', ['discogs_artist_id'], unique=True)
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_index(op.f('ix_artists_owner_id'),
                    'artists', ['owner_id'], unique=False)
    op.create_table('collections',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=True),
                    sa.Column('is_public', sa.Boolean(), nullable=False),
                    sa.Column('mood', sa.Enum('HAPPY', 'SAD', 'EXCITED', 'CALM', 'ANGRY', 'RELAXED', 'ENERGETIC',
                                              'MELANCHOLIC', name='moodenum', create_type=False), nullable=True, comment='Mood of this collection'),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.Column('registered_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.CheckConstraint('length(name) >= 1',
                                       name='check_collection_name_length'),
                    sa.ForeignKeyConstraint(
                        ['owner_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_collections_id'),
                    'collections', ['id'], unique=False)
    op.create_index(op.f('ix_collections_name'),
                    'collections', ['name'], unique=False)
    op.create_index(op.f('ix_collections_owner_id'),
                    'collections', ['owner_id'], unique=False)
    op.create_table('places',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('address', sa.String(length=255), nullable=True),
                    sa.Column('city', sa.String(length=100), nullable=True),
                    sa.Column('country', sa.String(length=100), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('type', sa.Enum('SHOP', 'VENUE', 'RECORD_STORE', 'OTHER', 'BROCANT',
                                              name='place_type_enum', create_type=False), server_default='OTHER', nullable=False),
                    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.CheckConstraint('latitude >= -90 AND latitude <= 90',
                                       name='check_latitude_range'),
                    sa.CheckConstraint('length(name) >= 1',
                                       name='check_place_name_length'),
                    sa.CheckConstraint(
                        'longitude >= -180 AND longitude <= 180', name='check_longitude_range'),
                    sa.ForeignKeyConstraint(['submitted_by_id'], [
                        'users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_places_city'), 'places', ['city'], unique=False)
    op.create_index(op.f('ix_places_country'),
                    'places', ['country'], unique=False)
    op.create_index(op.f('ix_places_id'), 'places', ['id'], unique=False)
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=False)
    op.create_index(op.f('ix_places_submitted_by_id'),
                    'places', ['submitted_by_id'], unique=False)
    op.create_table('wishlist',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False,
                              comment='ID of the user who owns this wishlist entry'),
                    sa.Column('external_id', sa.String(length=255), nullable=False,
                              comment='External ID of the album or artist'),
                    sa.Column('source', sa.Enum('DEEZER', 'SPOTIFY', 'MUSICBRAINZ', 'DISCOGS', 'LAST_FM', name='externalsourceenum', create_type=False),
                              server_default='DISCOGS', nullable=False, comment='Source of the external album ID'),
                    sa.Column('entity_type', sa.Enum('ALBUM', 'ARTIST', name='entitytypeenum', create_type=False),
                              nullable=False, comment='Type of entity (ALBUM or ARTIST)'),
                    sa.Column('title', sa.String(length=512), nullable=True,
                              comment='Cached name of the artist or album'),
                    sa.Column('image_url', sa.String(length=1024), nullable=True,
                              comment='Cached image URL for the artist or album'),
                    sa.Column('created_at', sa.DateTime(), nullable=False,
                              comment='When this wishlist entry was created'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'external_id', 'entity_type',
                                        'source', name='uq_user_external_entity_source')
                    )
    op.create_index(op.f('ix_wishlist_entity_type'),
                    'wishlist', ['entity_type'], unique=False)
    op.create_index(op.f('ix_wishlist_external_id'),
                    'wishlist', ['external_id'], unique=False)
    op.create_index(op.f('ix_wishlist_id'), 'wishlist', ['id'], unique=False)
    op.create_index(op.f('ix_wishlist_user_id'),
                    'wishlist', ['user_id'], unique=False)
    op.create_table('album_artist',
                    sa.Column('album_id', sa.Integer(), nullable=False),
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['album_id'], ['albums.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['artist_id'], ['artists.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('album_id', 'artist_id')
                    )
    op.create_table('collection_album',
                    sa.Column('collection_id', sa.Integer(), nullable=False),
                    sa.Column('album_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['album_id'], ['albums.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['collection_id'], ['collections.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('collection_id', 'album_id')
                    )
    op.create_table('collection_artist',
                    sa.Column('collection_id', sa.Integer(), nullable=False),
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['artist_id'], ['artists.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['collection_id'], ['collections.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('collection_id', 'artist_id')
                    )
    op.create_table('collection_likes',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('collection_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['collection_id'], ['collections.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'collection_id')
                    )
    op.create_table('likes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('collection_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['collection_id'], ['collections.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_likes_collection_id'), 'likes',
                    ['collection_id'], unique=False)
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes',
                    ['user_id'], unique=False)
    op.create_table('loans',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('album_id', sa.Integer(), nullable=False),
                    sa.Column('loaned_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('returned_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('comment', sa.String(length=255), nullable=True),
                    sa.Column('borrower_name', sa.String(
                        length=255), nullable=False),
                    sa.Column('start_date', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('end_date', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('is_returned', sa.Boolean(), nullable=False),
                    sa.CheckConstraint('length(comment) <= 255',
                                       name='check_comment_length'),
                    sa.ForeignKeyConstraint(
                        ['album_id'], ['albums.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_loans_album_id'), 'loans',
                    ['album_id'], unique=False)
    op.create_index(op.f('ix_loans_borrower_name'), 'loans',
                    ['borrower_name'], unique=False)
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_user_id'), 'loans',
                    ['user_id'], unique=False)
    op.create_table('moderation_requests',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('target_type', sa.String(
                        length=50), nullable=False),
                    sa.Column('target_id', sa.Integer(), nullable=False),
                    sa.Column('reason', sa.String(length=255), nullable=False),
                    sa.Column('is_resolved', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('place_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED',
                                                name='moderationstatusenum', create_type=False), nullable=False),
                    sa.Column('submitted_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['place_id'], ['places.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_moderation_requests_id'),
                    'moderation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_moderation_requests_place_id'),
                    'moderation_requests', ['place_id'], unique=False)
    op.create_index(op.f('ix_moderation_requests_user_id'),
                    'moderation_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moderation_requests_user_id'),
                  table_name='moderation_requests')
    op.drop_index(op.f('ix_moderation_requests_place_id'),
                  table_name='moderation_requests')
    op.drop_index(op.f('ix_moderation_requests_id'),
                  table_name='moderation_requests')
    op.drop_table('moderation_requests')
    op.drop_index(op.f('ix_loans_user_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_borrower_name'), table_name='loans')
    op.drop_index(op.f('ix_loans_album_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_collection_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_table('collection_likes')
    op.drop_table('collection_artist')
    op.drop_table('collection_album')
    op.drop_table('album_artist')
    op.drop_index(op.f('ix_wishlist_user_id'), table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_id'), table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_external_id'), table_name='wishlist')
    op.drop_index(op.f('ix_wishlist_entity_type'), table_name='wishlist')
    op.drop_table('wishlist')
    op.drop_index(op.f('ix_places_submitted_by_id'), table_name='places')
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_index(op.f('ix_places_id'), table_name='places')
    op.drop_index(op.f('ix_places_country'), table_name='places')
    op.drop_index(op.f('ix_places_city'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_collections_owner_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_artists_owner_id'), table_name='artists')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_index(op.f('ix_artists_discogs_artist_id'), table_name='artists')
    op.drop_table('artists')
    op.drop_index(op.f('ix_albums_owner_id'), table_name='albums')
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    op.drop_index(op.f('ix_albums_external_album_id'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
