"""updating ARTIST and wish agai5  MODEL

Revision ID: 7ba7696c9ee3
Revises: 418aad008764
Create Date: 2025-06-15 08:02:32.931413+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ba7696c9ee3'
down_revision: Union[str, None] = '418aad008764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'external_artist_id',
               existing_type=sa.VARCHAR(length=255),
               comment='External Artist ID as string',
               existing_comment='Discogs Artist ID as string',
               existing_nullable=False)
    op.alter_column('wishlist', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID of the user who owns this wishlist entry',
               existing_nullable=False)
    op.alter_column('wishlist', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='External ID of the album or artist',
               existing_nullable=False)
    op.alter_column('wishlist', 'source',
               existing_type=postgresql.ENUM('DEEZER', 'SPOTIFY', 'MUSICBRAINZ', 'DISCOGS', 'LAST_FM', name='externalsourceenum'),
               comment=None,
               existing_comment='Source of the external album ID',
               existing_nullable=False,
               existing_server_default=sa.text("'DISCOGS'::externalsourceenum"))
    op.alter_column('wishlist', 'entity_type',
               existing_type=postgresql.ENUM('ALBUM', 'ARTIST', name='entitytypeenum'),
               comment=None,
               existing_comment='Type of entity (ALBUM or ARTIST)',
               existing_nullable=False)
    op.alter_column('wishlist', 'title',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Cached name of the artist or album',
               existing_nullable=True)
    op.alter_column('wishlist', 'image_url',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='Cached image URL for the artist or album',
               existing_nullable=True)
    op.alter_column('wishlist', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When this wishlist entry was created',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlist', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='When this wishlist entry was created',
               existing_nullable=False)
    op.alter_column('wishlist', 'image_url',
               existing_type=sa.VARCHAR(length=1024),
               comment='Cached image URL for the artist or album',
               existing_nullable=True)
    op.alter_column('wishlist', 'title',
               existing_type=sa.VARCHAR(length=512),
               comment='Cached name of the artist or album',
               existing_nullable=True)
    op.alter_column('wishlist', 'entity_type',
               existing_type=postgresql.ENUM('ALBUM', 'ARTIST', name='entitytypeenum'),
               comment='Type of entity (ALBUM or ARTIST)',
               existing_nullable=False)
    op.alter_column('wishlist', 'source',
               existing_type=postgresql.ENUM('DEEZER', 'SPOTIFY', 'MUSICBRAINZ', 'DISCOGS', 'LAST_FM', name='externalsourceenum'),
               comment='Source of the external album ID',
               existing_nullable=False,
               existing_server_default=sa.text("'DISCOGS'::externalsourceenum"))
    op.alter_column('wishlist', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               comment='External ID of the album or artist',
               existing_nullable=False)
    op.alter_column('wishlist', 'user_id',
               existing_type=sa.INTEGER(),
               comment='ID of the user who owns this wishlist entry',
               existing_nullable=False)
    op.alter_column('artists', 'external_artist_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Discogs Artist ID as string',
               existing_comment='External Artist ID as string',
               existing_nullable=False)
    # ### end Alembic commands ###
