"""move_owner_id_to_association_tables

Revision ID: 82796b1fe092
Revises: 732383254a21
Create Date: 2025-06-15 16:32:51.926805+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82796b1fe092'
down_revision: Union[str, None] = '732383254a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns (temporarily nullable)
    op.add_column('collection_album', sa.Column(
        'owner_id', sa.Integer(), nullable=True))
    op.add_column('collection_artist', sa.Column(
        'owner_id', sa.Integer(), nullable=True))

    # Copy data from albums and artists to association tables
    op.execute("""
        UPDATE collection_album ca
        SET owner_id = a.owner_id
        FROM albums a
        WHERE ca.album_id = a.id
    """)

    op.execute("""
        UPDATE collection_artist ca
        SET owner_id = a.owner_id
        FROM artists a
        WHERE ca.artist_id = a.id
    """)

    # Make columns non-nullable
    op.alter_column('collection_album', 'owner_id', nullable=False)
    op.alter_column('collection_artist', 'owner_id', nullable=False)

    # Create indexes and foreign keys
    op.create_index(op.f('ix_collection_album_owner_id'),
                    'collection_album', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'collection_album', 'users', [
                          'owner_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_collection_artist_owner_id'),
                    'collection_artist', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'collection_artist', 'users', [
                          'owner_id'], ['id'], ondelete='CASCADE')

    # Remove old columns
    op.drop_index(op.f('ix_albums_owner_id'), table_name='albums')
    op.drop_constraint(op.f('albums_owner_id_fkey'),
                       'albums', type_='foreignkey')
    op.drop_column('albums', 'owner_id')
    op.drop_index(op.f('ix_artists_owner_id'), table_name='artists')
    op.drop_constraint(op.f('artists_owner_id_fkey'),
                       'artists', type_='foreignkey')
    op.drop_column('artists', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection_artist', type_='foreignkey')
    op.drop_index(op.f('ix_collection_artist_owner_id'),
                  table_name='collection_artist')
    op.drop_column('collection_artist', 'owner_id')
    op.drop_constraint(None, 'collection_album', type_='foreignkey')
    op.drop_index(op.f('ix_collection_album_owner_id'),
                  table_name='collection_album')
    op.drop_column('collection_album', 'owner_id')
    op.add_column('artists', sa.Column('owner_id', sa.INTEGER(), autoincrement=False,
                  nullable=False, comment='ID of the user who owns this artist entry'))
    op.create_foreign_key(op.f('artists_owner_id_fkey'), 'artists', 'users', [
                          'owner_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_artists_owner_id'),
                    'artists', ['owner_id'], unique=False)
    op.add_column('albums', sa.Column('owner_id', sa.INTEGER(
    ), autoincrement=False, nullable=False, comment='ID of the user who owns this album'))
    op.create_foreign_key(op.f('albums_owner_id_fkey'), 'albums', 'users', [
                          'owner_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_albums_owner_id'),
                    'albums', ['owner_id'], unique=False)
    # ### end Alembic commands ###
