"""update_user_schema

Revision ID: 84f205cbd5c8
Revises: f4fd7da78368
Create Date: 2025-05-26 19:58:21.023918+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f205cbd5c8'
down_revision: Union[str, None] = 'f4fd7da78368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('number_of_connections', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'number_of_connections')
    # ### end Alembic commands ###
