"""add_unique_constraint_collection_name_per_user

Revision ID: b6acf817fef8
Revises: becc11fa7f58
Create Date: 2025-09-07 15:40:17.891100+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6acf817fef8'
down_revision: Union[str, None] = 'becc11fa7f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_collection_name', 'collections', ['owner_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_collection_name', 'collections', type_='unique')
    # ### end Alembic commands ###
