"""sync_models_with_db_after_index_cleanup

Revision ID: becc11fa7f58
Revises: 48aee46d80a2
Create Date: 2025-09-07 10:29:42.284032+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'becc11fa7f58'
down_revision: Union[str, None] = '48aee46d80a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes that are no longer needed
    op.drop_index(op.f('ix_collection_album_collection_id'), table_name='collection_album')
    op.drop_index(op.f('ix_collection_artist_collection_id'), table_name='collection_artist')
    op.drop_index(op.f('ix_places_is_moderated'), table_name='places')
    op.drop_index(op.f('ix_wishlist_user_id_entity_type'), table_name='wishlist')
    # Note: uq_collection_album already exists as primary key composite constraint
    # No need to create it again
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wishlist_user_id_entity_type'), 'wishlist', ['user_id', 'entity_type_id'], unique=False)
    op.create_index(op.f('ix_places_is_moderated'), 'places', ['is_moderated'], unique=False)
    op.create_index(op.f('ix_collection_artist_collection_id'), 'collection_artist', ['collection_id'], unique=False)
    # Note: uq_collection_album is a primary key constraint, not a unique constraint
    # Cannot drop primary key constraint in downgrade
    op.create_index(op.f('ix_collection_album_collection_id'), 'collection_album', ['collection_id'], unique=False)
    # ### end Alembic commands ###
