"""move_album_instance_fields_to_collection_album

Revision ID: de648ccdb1ff
Revises: 82796b1fe092
Create Date: 2025-06-15 16:37:01.324719+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de648ccdb1ff'
down_revision: Union[str, None] = '82796b1fe092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns to collection_album
    op.add_column('collection_album', sa.Column('state_record', sa.Enum('MINT', 'NEAR_MINT', 'VERY_GOOD',
                  'GOOD', 'FAIR', 'POOR', name='stateenum'), nullable=True, comment='Physical state of the vinyl record'))
    op.add_column('collection_album', sa.Column('state_cover', sa.Enum('MINT', 'NEAR_MINT', 'VERY_GOOD',
                  'GOOD', 'FAIR', 'POOR', name='stateenum'), nullable=True, comment='Physical state of the album cover'))
    op.add_column('collection_album', sa.Column('mood', sa.Enum('HAPPY', 'SAD', 'EXCITED', 'CALM', 'ANGRY', 'RELAXED',
                  'ENERGETIC', 'MELANCHOLIC', name='moodenum'), nullable=True, comment='Mood associated with this album'))
    op.add_column('collection_album', sa.Column('acquisition_date', sa.DateTime(
    ), nullable=True, comment='Date when the album was acquired'))
    op.add_column('collection_album', sa.Column('purchase_price', sa.Integer(
    ), nullable=True, comment='Price paid for the album in cents'))

    # Copy data from albums to collection_album
    op.execute("""
        UPDATE collection_album ca
        SET 
            state_record = a.state_record,
            state_cover = a.state_cover,
            mood = a.mood,
            acquisition_date = a.acquisition_date,
            purchase_price = a.purchase_price
        FROM albums a
        WHERE ca.album_id = a.id
    """)

    # Drop columns from albums
    op.drop_column('albums', 'state_cover')
    op.drop_column('albums', 'mood')
    op.drop_column('albums', 'state_record')
    op.drop_column('albums', 'purchase_price')
    op.drop_column('albums', 'acquisition_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_album', 'purchase_price')
    op.drop_column('collection_album', 'acquisition_date')
    op.drop_column('collection_album', 'mood')
    op.drop_column('collection_album', 'state_cover')
    op.drop_column('collection_album', 'state_record')
    op.add_column('albums', sa.Column('acquisition_date', postgresql.TIMESTAMP(
    ), autoincrement=False, nullable=True, comment='Date when the album was acquired'))
    op.add_column('albums', sa.Column('purchase_price', sa.INTEGER(
    ), autoincrement=False, nullable=True, comment='Price paid for the album in cents'))
    op.add_column('albums', sa.Column('state_record', postgresql.ENUM('MINT', 'NEAR_MINT', 'VERY_GOOD', 'GOOD', 'FAIR',
                  'POOR', name='stateenum'), autoincrement=False, nullable=True, comment='Physical state of the vinyl record'))
    op.add_column('albums', sa.Column('mood', postgresql.ENUM('HAPPY', 'SAD', 'EXCITED', 'CALM', 'ANGRY', 'RELAXED', 'ENERGETIC',
                  'MELANCHOLIC', name='moodenum'), autoincrement=False, nullable=True, comment='Mood associated with this album'))
    op.add_column('albums', sa.Column('state_cover', postgresql.ENUM('MINT', 'NEAR_MINT', 'VERY_GOOD', 'GOOD', 'FAIR',
                  'POOR', name='stateenum'), autoincrement=False, nullable=True, comment='Physical state of the album cover'))
    # ### end Alembic commands ###
