"""updating ARTIST enum MODEL

Revision ID: e0afe09f40b7
Revises: eed7c24f65fa
Create Date: 2025-06-15 07:31:28.436042+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0afe09f40b7'
down_revision: Union[str, None] = 'eed7c24f65fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'source',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('DEEZER', 'SPOTIFY', 'MUSICBRAINZ', 'DISCOGS', 'LAST_FM', name='externalsourceenum'),
               existing_comment='Source of the artist data',
               existing_nullable=False,
               existing_server_default=sa.text("'discogs'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'source',
               existing_type=sa.Enum('DEEZER', 'SPOTIFY', 'MUSICBRAINZ', 'DISCOGS', 'LAST_FM', name='externalsourceenum'),
               type_=sa.VARCHAR(length=255),
               existing_comment='Source of the artist data',
               existing_nullable=False,
               existing_server_default=sa.text("'discogs'::character varying"))
    # ### end Alembic commands ###
