"""updating ARTIST id  MODEL

Revision ID: eaa048d59b03
Revises: e0afe09f40b7
Create Date: 2025-06-15 07:42:51.516713+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa048d59b03'
down_revision: Union[str, None] = 'e0afe09f40b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('external_artist_id', sa.String(length=255), nullable=False, comment='Discogs Artist ID as string'))
    op.drop_index(op.f('ix_artists_discogs_artist_id'), table_name='artists')
    op.create_index(op.f('ix_artists_external_artist_id'), 'artists', ['external_artist_id'], unique=True)
    op.drop_column('artists', 'discogs_artist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('discogs_artist_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Discogs Artist ID as string'))
    op.drop_index(op.f('ix_artists_external_artist_id'), table_name='artists')
    op.create_index(op.f('ix_artists_discogs_artist_id'), 'artists', ['discogs_artist_id'], unique=True)
    op.drop_column('artists', 'external_artist_id')
    # ### end Alembic commands ###
