"""updating ARTIST MODEL

Revision ID: eed7c24f65fa
Revises: 420295606859
Create Date: 2025-06-15 07:28:38.262363+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed7c24f65fa'
down_revision: Union[str, None] = '420295606859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('title', sa.String(
        length=512), nullable=True, comment='Name of the artist'))
    op.add_column('artists', sa.Column('image_url', sa.String(
        length=1024), nullable=True, comment='URL of the artist image'))
    op.add_column('artists', sa.Column('source', sa.Enum(
        'DISCOGS', 'SPOTIFY', 'DEEZER', 'YOUTUBE', name='externalsourceenum', create_type=False), server_default='DISCOGS', nullable=False, comment='Source of the artist data'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'source')
    op.drop_column('artists', 'image_url')
    op.drop_column('artists', 'title')
    # ### end Alembic commands ###
