"""add_image_fields_to_external_references

Revision ID: 561125b61622
Revises: b74f0eef3372
Create Date: 2025-05-30 16:42:17.712449+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561125b61622'
down_revision: Union[str, None] = 'b74f0eef3372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_references', sa.Column('picture_small', sa.String(length=500), nullable=True))
    op.add_column('external_references', sa.Column('picture_medium', sa.String(length=500), nullable=True))
    op.add_column('external_references', sa.Column('picture_big', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_references', 'picture_big')
    op.drop_column('external_references', 'picture_medium')
    op.drop_column('external_references', 'picture_small')
    # ### end Alembic commands ###
