"""add owner relation for collections display

Revision ID: 7627823c1af6
Revises: a8eb13d466fb
Create Date: 2025-05-30 14:57:31.257093+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7627823c1af6'
down_revision: Union[str, None] = 'a8eb13d466fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
