"""add missing album relations for loans and wishlist

Revision ID: a2efc4e750d6
Revises: c5cbfa80891a
Create Date: 2025-05-30 14:29:56.058219+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2efc4e750d6'
down_revision: Union[str, None] = 'c5cbfa80891a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
