"""add_external_references_and_update_wishlist_collection

Revision ID: fccaddb8e6cb
Revises: 7627823c1af6
Create Date: 2025-05-30 16:23:13.666129+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fccaddb8e6cb'
down_revision: Union[str, None] = '7627823c1af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('external_source', sa.Enum('DEEZER', 'SPOTIFY', 'MUSICBRAINZ', name='externalsourceenum'), nullable=False),
    sa.Column('item_type', sa.Enum('ALBUM', 'ARTIST', name='externalitemtypeenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('artist_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_references_external_id'), 'external_references', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_references_id'), 'external_references', ['id'], unique=False)
    op.create_table('collection_external_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('external_reference_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['external_reference_id'], ['external_references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_external_references_id'), 'collection_external_references', ['id'], unique=False)
    op.add_column('wishlists', sa.Column('external_reference_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wishlists', 'external_references', ['external_reference_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlists', type_='foreignkey')
    op.drop_column('wishlists', 'external_reference_id')
    op.drop_index(op.f('ix_collection_external_references_id'), table_name='collection_external_references')
    op.drop_table('collection_external_references')
    op.drop_index(op.f('ix_external_references_id'), table_name='external_references')
    op.drop_index(op.f('ix_external_references_external_id'), table_name='external_references')
    op.drop_table('external_references')
    # ### end Alembic commands ###
