//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "albums")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub external_album_id: String,
    pub title: Option<String>,
    pub external_source_id: i32,
    pub image_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_album::Entity")]
    CollectionAlbum,
    #[sea_orm(
        belongs_to = "super::external_sources::Entity",
        from = "Column::ExternalSourceId",
        to = "super::external_sources::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ExternalSources,
    #[sea_orm(has_many = "super::loans::Entity")]
    Loans,
}

impl Related<super::collection_album::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionAlbum.def()
    }
}

impl Related<super::external_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExternalSources.def()
    }
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
