//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "artists")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub external_artist_id: String,
    pub title: Option<String>,
    pub image_url: Option<String>,
    pub external_source_id: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_artist::Entity")]
    CollectionArtist,
    #[sea_orm(
        belongs_to = "super::external_sources::Entity",
        from = "Column::ExternalSourceId",
        to = "super::external_sources::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ExternalSources,
}

impl Related<super::collection_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionArtist.def()
    }
}

impl Related<super::external_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExternalSources.def()
    }
}

impl Related<super::collections::Entity> for Entity {
    fn to() -> RelationDef {
        super::collection_artist::Relation::Collections.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::collection_artist::Relation::Artists.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
