//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "collections")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub is_public: bool,
    pub mood_id: Option<i32>,
    pub owner_id: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_album::Entity")]
    CollectionAlbum,
    #[sea_orm(has_many = "super::collection_artist::Entity")]
    CollectionArtist,
    #[sea_orm(has_many = "super::likes::Entity")]
    Likes,
    #[sea_orm(
        belongs_to = "super::moods::Entity",
        from = "Column::MoodId",
        to = "super::moods::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Moods,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::collection_album::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionAlbum.def()
    }
}

impl Related<super::collection_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionArtist.def()
    }
}

impl Related<super::likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Likes.def()
    }
}

impl Related<super::moods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Moods.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::artists::Entity> for Entity {
    fn to() -> RelationDef {
        super::collection_artist::Relation::Artists.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::collection_artist::Relation::Collections.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
