//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "collection_album")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub collection_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub album_id: i32,
    pub state_record: Option<i32>,
    pub state_cover: Option<i32>,
    pub acquisition_month_year: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::albums::Entity",
        from = "Column::AlbumId",
        to = "super::albums::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Albums,
    #[sea_orm(
        belongs_to = "super::collections::Entity",
        from = "Column::CollectionId",
        to = "super::collections::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Collections,
    #[sea_orm(
        belongs_to = "super::vinyl_states::Entity",
        from = "Column::StateCover",
        to = "super::vinyl_states::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    VinylStates2,
    #[sea_orm(
        belongs_to = "super::vinyl_states::Entity",
        from = "Column::StateRecord",
        to = "super::vinyl_states::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    VinylStates1,
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Albums.def()
    }
}

impl Related<super::collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Collections.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
