//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod albums;
pub mod alembic_version;
pub mod artists;
pub mod collection_album;
pub mod collection_artist;
pub mod collections;
pub mod entity_types;
pub mod external_sources;
pub mod likes;
pub mod loans;
pub mod moderation_requests;
pub mod moderation_statuses;
pub mod moods;
pub mod place_likes;
pub mod place_types;
pub mod places;
pub mod roles;
pub mod users;
pub mod vinyl_states;
pub mod wishlist;
