//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "moderation_statuses")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::moderation_requests::Entity")]
    ModerationRequests,
}

impl Related<super::moderation_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModerationRequests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
