//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "places")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub address: Option<String>,
    pub city: Option<String>,
    pub country: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub latitude: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub longitude: Option<f64>,
    pub place_type_id: i32,
    pub submitted_by_id: Option<i32>,
    pub is_moderated: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub description: Option<String>,
    pub source_url: Option<String>,
    pub is_valid: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::moderation_requests::Entity")]
    ModerationRequests,
    #[sea_orm(has_many = "super::place_likes::Entity")]
    PlaceLikes,
    #[sea_orm(
        belongs_to = "super::place_types::Entity",
        from = "Column::PlaceTypeId",
        to = "super::place_types::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PlaceTypes,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::SubmittedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::moderation_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModerationRequests.def()
    }
}

impl Related<super::place_likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaceLikes.def()
    }
}

impl Related<super::place_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaceTypes.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
