//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub is_accepted_terms: bool,
    pub is_active: bool,
    pub is_superuser: bool,
    pub last_login: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub timezone: String,
    pub role_id: i32,
    #[sea_orm(unique)]
    pub user_uuid: Uuid,
    pub number_of_connections: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collections::Entity")]
    Collections,
    #[sea_orm(has_many = "super::likes::Entity")]
    Likes,
    #[sea_orm(has_many = "super::loans::Entity")]
    Loans,
    #[sea_orm(has_many = "super::moderation_requests::Entity")]
    ModerationRequests,
    #[sea_orm(has_many = "super::place_likes::Entity")]
    PlaceLikes,
    #[sea_orm(has_many = "super::places::Entity")]
    Places,
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::RoleId",
        to = "super::roles::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Roles,
    #[sea_orm(has_many = "super::wishlist::Entity")]
    Wishlist,
}

impl Related<super::collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Collections.def()
    }
}

impl Related<super::likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Likes.def()
    }
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl Related<super::moderation_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModerationRequests.def()
    }
}

impl Related<super::place_likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaceLikes.def()
    }
}

impl Related<super::places::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Places.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::wishlist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wishlist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
