//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wishlist")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub external_id: String,
    pub entity_type_id: i32,
    pub external_source_id: i32,
    pub title: Option<String>,
    pub image_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::entity_types::Entity",
        from = "Column::EntityTypeId",
        to = "super::entity_types::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EntityTypes,
    #[sea_orm(
        belongs_to = "super::external_sources::Entity",
        from = "Column::ExternalSourceId",
        to = "super::external_sources::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ExternalSources,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::entity_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntityTypes.def()
    }
}

impl Related<super::external_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExternalSources.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
