"""update collection model for new endpoints

Revision ID: 4d97a2a634b2
Revises: c024937deb1c
Create Date: 2025-05-30 14:26:27.953705+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d97a2a634b2'
down_revision: Union[str, None] = 'c024937deb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_album',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'album_id')
    )
    op.create_table('collection_artist',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'artist_id')
    )
    op.create_table('collection_genre',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'genre_id')
    )
    op.drop_constraint(op.f('albums_collection_id_fkey'), 'albums', type_='foreignkey')
    op.drop_column('albums', 'collection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('albums_collection_id_fkey'), 'albums', 'collections', ['collection_id'], ['id'])
    op.drop_table('collection_genre')
    op.drop_table('collection_artist')
    op.drop_table('collection_album')
    # ### end Alembic commands ###
