"""fix_external_references_many_to_many_collections

Revision ID: b74f0eef3372
Revises: fccaddb8e6cb
Create Date: 2025-05-30 16:32:05.957153+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74f0eef3372'
down_revision: Union[str, None] = 'fccaddb8e6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
