"""set_default_value_number_of_connections

Revision ID: c024937deb1c
Revises: 84f205cbd5c8
Create Date: 2025-05-26 20:13:11.841499+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c024937deb1c'
down_revision: Union[str, None] = '84f205cbd5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
